
actions:
  - name: "Run locust"
    event: "sh.keptn.event.test.triggered"
    jsonpath:
      property: "$.data.test.teststrategy" 
      match: "locust"
    tasks:
      - name: "Run locust smoke tests"
        files: 
          - locust/basic.py
          - locust/import.py
        image: "locustio/locust"
        cmd: "locust -f /keptn/locust/locustfile.py"

  - name: "Run Bash"
    event: "sh.keptn.event.action.triggered"
    jsonpath: 
      property: "$.data.action.action"
      match: "hello"
    tasks:
      - name: "Run static world"
        image: "bash"
        cmd: "echo static"
      - name: "Run hello world"
        files: 
          - hello/hello-world.txt
        image: "bash"
        cmd: "cat /keptn/hello/hello-world.txt | echo"
